<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/11
 * Time: 11:39
 */

namespace backend\controllers;

use backend\models\Config;
use yii\helpers\Json;
use Yii;

class ConfigController extends CommonController
{
    public $enableCsrfValidation = false;
    public $layout = false;
    public $configModel;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->configModel = new Config();
    }
    /*
     * 基本设置信息
     */
    public function actionIndex(){
        if(Yii::$app->request->isPost){
            //接收数据
            $post = Yii::$app->request->post();
            //判断是否有上传图片
            if ($_FILES["Config"]['error']['con_logo'] == 0) {
                //上传logo图片
                $upload = Yii::$app->imgoperate->UploadImg($this->configModel,'con_logo','uploads/config',Yii::getAlias('@frontend').'/web',false);
                //图片上传成功
                if($upload['code'] == 1){
                    //图片路径
                    $post['Config']['con_logo'] = $upload['img_url'];
                    //删除旧图
                    $config_logo = $this->configModel->find()->select('con_logo')->where(['id'=>$post['Config']['id']])->asArray()->one();
                    if($config_logo['con_logo']){
                        $old_path = Yii::getAlias('@frontend') . '/web' . $config_logo['con_logo'];
                        @unlink($old_path);
                    }
                }else{
                    $data['code'] = 0;
                    $data['msg'] = $upload['msg'];
                    return Json::encode($data);
                }
            }
            //修改数据
            if ($this->configModel->updateAll($post['Config'],['id'=>$post['Config']['id']])) {
                $data['code'] = 1;
                $data['msg'] = '更新成功!';
                return Json::encode($data);
            } else {
                $data['code'] = 0;
                $data['msg'] = '更新失败!';
                return Json::encode($data);
            }

        }else{
            //读取基本设置信息
            $config_info = $this->configModel->find()->asArray()->one();
            return $this->render('index',['config_info'=>$config_info]);
        }
    }

}