<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/11
 * Time: 16:12
 */

namespace backend\controllers;

use backend\models\Nav;
use yii\data\Pagination;
use yii\helpers\Json;
use Yii;

class NavController extends CommonController
{
    public $enableCsrfValidation = false;
    public $layout = false;
    public $navModel;
    public function init(){
        parent::init(); // TODO: Change the autogenerated stub
        $this->navModel = new Nav();
    }
    /*
     * 导航列表
     */
    public function actionNav_list(){
        return $this->render('nav_list');
    }
    public function actionList_data(){
        //获取分页的page和limit
        $get_data = Yii::$app->request->get();
        //每页条数
        $get_data['limit'] = $get_data['limit']?$get_data['limit']:10;
        //读取数据并进行分页
        $nav = $this->navModel->find();
        $pages = new Pagination(['totalCount'=>$nav->count(),'pageSize'=>$get_data['limit']]);
        $list = $nav->offset($pages->offset)->limit($pages->limit)->orderBy('nav_level DESC')->asArray()->all();
        //总条数
        $totalCount = $pages->totalCount;
        //转换成json格式
        $list_json = Json::encode($list);
        //拼接json数据
        $json_data = '{"code":0,"msg":"","count":'.$totalCount.',"data":'.$list_json.'}';
        return $json_data;
    }
    /*
     * 添加导航
     */
    public function actionNav_add(){
        if(Yii::$app->request->isPost){
            //接收提交的数据
            $post = Yii::$app->request->post();
            //导航状态赋值
            if(isset($post['Nav']['nav_state']) && $post['Nav']['nav_state'] == 'on'){
                $post['Nav']['nav_state'] = 1;
            }else{
                $post['Nav']['nav_state'] = 0;
            }
            //添加数据
            $this->navModel->load($post);
            if($this->navModel->save(false)){
                $data['code'] = 1;
                $data['msg'] = '添加成功!';
                return Json::encode($data);
            }else{
                $data['code'] = 0;
                $data['msg'] = '添加失败!';
                return Json::encode($data);
            }
        }else{
            return $this->render('nav_add');
        }
    }
    /*
     * 修改导航
     */
    public function actionNav_edit(){
        if(Yii::$app->request->isPost){
            //接收提交的数据
            $post = Yii::$app->request->post();
            //导航状态赋值
            if(isset($post['Nav']['nav_state']) && $post['Nav']['nav_state'] == 'on'){
                $post['Nav']['nav_state'] = 1;
            }else{
                $post['Nav']['nav_state'] = 0;
            }
            //修改数据
            if ($this->navModel->updateAll($post['Nav'],['id'=>$post['Nav']['id']])) {
                $data['code'] = 1;
                $data['msg'] = '修改成功!';
                return Json::encode($data);
            } else {
                $data['code'] = 0;
                $data['msg'] = '修改失败!';
                return Json::encode($data);
            }
        }else{
            //获取id
            $id = Yii::$app->request->get('id');
            if($id){
                //根据ID查询要修改的数据
                $nav_info = $this->navModel->find()->where(['id'=>$id])->asArray()->one();
                if($nav_info){
                    return $this->render('nav_edit',['nav_info'=>$nav_info]);
                }else{
                    return $this->redirect(['/site/error_404', '该数据不存在!']);
                }
            }else{
                return $this->redirect(['/site/error_404', '参数错误!']);
            }
        }
    }
    /*
     * 删除导航
     */
    public function actionNav_del(){
        if(Yii::$app->request->isPost){
            //获取id
            $id = Yii::$app->request->post("id");
            //删除数据
            if ($this->navModel->findOne($id)->delete()) {
                $info['code'] = 1;
                $info['msg'] = "删除成功!";
                return Json::encode($info);
            } else {
                $info['code'] = 0;
                $info['msg'] = "删除失败!";
                return Json::encode($info);
            }
        }
    }
}