<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/12
 * Time: 14:12
 */

namespace backend\controllers;

use backend\models\News;
use backend\models\Config;
use Yii;
use yii\data\Pagination;
use yii\helpers\Json;

class NewsController extends CommonController
{
    public $enableCsrfValidation = false;
    public $layout = false;
    public $newsModel;
    public $configModel;
    public $con_prefix;
    public function init(){
        parent::init(); // TODO: Change the autogenerated stub
        $this->newsModel = new News();
        $this->configModel = new Config();
        //图片访问路径前缀
        $prefix = $this->configModel->find()->select('con_prefix')->asArray()->one();
        $this->con_prefix = $prefix['con_prefix'];
    }
    //编辑器配置文件
    public function actions()
    {
        //图片保存路径
//        $site = Yii::getAlias('@frontend').'/web/uploads/ueditor/nwes/';
        $site = '/uploads/ueditor/nwes/';
        $path = $site."{yyyy}{mm}{dd}/{time}{rand:6}";
        return [
            'ueditor' => [
                'class' => 'common\widgets\ueditor\UeditorAction',
                'config' => [
                    //上传图片配置
                    'imageUrlPrefix' => $this->con_prefix, /* 图片访问路径前缀 */
                    'imagePathFormat' => $path, /* 上传保存路径,可以自定义保存路径和文件名格式 */
                    'imageManagerListPath' => $site,/* 图片在线管理，指定要列出图片的目录 */
                    "initialFrameHeight" => 400,
                    "autoHeightEnabled" => false,
                    "scaleEnabled" => true,
                ]
            ]
        ];
    }
    /*
     * 新闻列表
     */
    public function actionNews_list(){
        return $this->render('news_list',['con_prefix'=>$this->con_prefix]);
    }
    public function actionList_data(){
        //获取分页的page和limit
        $get_data = Yii::$app->request->get();
        //每页条数
        $get_data['limit'] = $get_data['limit']?$get_data['limit']:10;
        //读取数据并进行分页
        $news = $this->newsModel->find();
        $pages = new Pagination(['totalCount'=>$news->count(),'pageSize'=>$get_data['limit']]);
        $list = $news->offset($pages->offset)->limit($pages->limit)->orderBy('new_time DESC')->asArray()->all();
        //转换时间格式
        foreach($list as $key=>$value){
            $list[$key]['new_time'] = date('Y/m/d H:i:s',$value['new_time']);
        }
        //总条数
        $totalCount = $pages->totalCount;
        //转换成json格式
        $list_json = Json::encode($list);
        //拼接json数据
        $json_data = '{"code":0,"msg":"","count":'.$totalCount.',"data":'.$list_json.'}';
        return $json_data;
    }
    /*
     * 添加新闻
     */
    public function actionNews_add(){
        if(Yii::$app->request->isPost){
            //接收提交的数据
            $post = Yii::$app->request->post();
            //判断是否有上传图片
            if ($_FILES["News"]['error']['new_img'] == 0) {
                //上传图片
                $upload = Yii::$app->imgoperate->UploadImg($this->newsModel,'new_img','uploads/news',Yii::getAlias('@frontend').'/web',false);
                //图片上传成功
                if($upload['code'] == 1){
                    //图片路径
                    $post['News']['new_img'] = $upload['img_url'];
                }else{
                    $data['code'] = 0;
                    $data['msg'] = $upload['msg'];
                    return Json::encode($data);
                }
            }
            //转换时间格式
            if (!empty($post["News"]['new_time'])) {
                $post["News"]['new_time'] = strtotime($post["News"]['new_time']);
            } else {
                $post["News"]['new_time'] = time();
            }
            //阅读量
            $post['News']['new_number'] = $post['News']['new_number']?$post['News']['new_number']:rand(300,500);
            //状态赋值
            if(isset($post['News']['new_state']) && $post['News']['new_state'] == 'on'){
                $post['News']['new_state'] = 1;
            }else{
                $post['News']['new_state'] = 0;
            }
            //替换新闻内容中的图片访问路径前缀'$this->con_prefix'为'{img}'
            $post['News']['new_content'] = str_replace($this->con_prefix,'{img}',$post['News']['new_content']);
            //添加数据
            $this->newsModel->load($post);
            if($this->newsModel->save(false)){
                $data['code'] = 1;
                $data['msg'] = '添加成功!';
                return Json::encode($data);
            }else{
                $data['code'] = 0;
                $data['msg'] = '添加失败!';
                return Json::encode($data);
            }
        }else{
            $this->layout = 'public';
            return $this->render('news_add');
        }
    }
    /*
     * 修改新闻
     */
    public function actionNews_edit(){
        if(Yii::$app->request->isPost){
            //接收提交的数据
            $post = Yii::$app->request->post();
            //判断是否有上传图片
            if ($_FILES["News"]['error']['new_img'] == 0) {
                //上传图片
                $upload = Yii::$app->imgoperate->UploadImg($this->newsModel,'new_img','uploads/news',Yii::getAlias('@frontend').'/web',false);
                //图片上传成功
                if($upload['code'] == 1){
                    //图片路径
                    $post['News']['new_img'] = $upload['img_url'];
                    //删除旧图
                    $new_img = $this->newsModel->find()->select('new_img')->where(['id'=>$post['News']['id']])->asArray()->one();
                    $old_path = Yii::getAlias('@frontend').'/web'.$new_img['new_img'];
                    @unlink($old_path);
                }else{
                    $data['code'] = 0;
                    $data['msg'] = $upload['msg'];
                    return Json::encode($data);
                }
            }
            //转换时间格式
            if (!empty($post["News"]['new_time'])) {
                $post["News"]['new_time'] = strtotime($post["News"]['new_time']);
            } else {
                $post["News"]['new_time'] = time();
            }
            //阅读量
            $post['News']['new_number'] = $post['News']['new_number']?$post['News']['new_number']:rand(300,500);
            //状态赋值
            if(isset($post['News']['new_state']) && $post['News']['new_state'] == 'on'){
                $post['News']['new_state'] = 1;
            }else{
                $post['News']['new_state'] = 0;
            }
            //替换新闻内容中的图片访问路径前缀'$this->con_prefix'为'{img}'
            $post['News']['new_content'] = str_replace($this->con_prefix,'{img}',$post['News']['new_content']);
            //修改数据
            if ($this->newsModel->updateAll($post['News'],['id'=>$post['News']['id']])){
                $data['code'] = 1;
                $data['msg'] = '修改成功!';
                return Json::encode($data);
            } else {
                $data['code'] = 0;
                $data['msg'] = '修改失败!';
                return Json::encode($data);
            }
        }else{
            $this->layout = 'public';
            //获取ID
            $id = Yii::$app->request->get('id');
            if($id){
                //根据ID查询要修改的数据
                $news_info = $this->newsModel->find()->where(['id'=>$id])->asArray()->one();
                if($news_info){
                    //转换时间格式
                    $news_info['new_time'] = date('Y/m/d H:i:s',$news_info['new_time']);
                    //替换新闻内容中的图片访问路径前缀'{img}'为'$this->con_prefix'
                    $news_info['new_content'] = str_replace('{img}',$this->con_prefix,$news_info['new_content']);
                    return $this->render('news_edit',['news_info'=>$news_info,'con_prefix'=>$this->con_prefix]);
                }else{
                    return $this->redirect(['/site/error_404', '该数据不存在!']);
                }

            }else{
                return $this->redirect(['/site/error_404', '参数错误!']);
            }

        }

    }
    /*
     * 删除新闻
     */
    public function actionNews_del(){
        if(Yii::$app->request->isPost){
            //获取ID
            $id = Yii::$app->request->post("id");
            //获取图片地址
            $new_img = $this->newsModel->find()->select('new_img')->where(['id'=>$id])->asArray()->one();
            //删除数据
            if ($this->newsModel->findOne($id)->delete()){
                //删除旧图
                if($new_img['new_img']){
                    $old_path = Yii::getAlias('@frontend').'/web'.$new_img['new_img'];
                    @unlink($old_path);
                }
                $info['code'] = 1;
                $info['msg'] = "删除成功!";
                return Json::encode($info);
            } else {
                $info['code'] = 0;
                $info['msg'] = "删除失败!";
                return Json::encode($info);
            }
        }
    }
    /*
     * 批量删除新闻
     */
    public function actionNews_delall(){
        if(Yii::$app->request->isPost){
            //获取ID
            $ids = Yii::$app->request->post("ids");
            if($ids){
                //判断$ids是否是个数组
                if(is_array($ids)){
                    //数组转成字符串
                    $ids = implode(',',$ids);
                }
                $where = 'id in('.$ids.')';
                //查找要删除的数据
                $lists = $this->newsModel->find()->select('new_img')->where($where)->asArray()->all();
                //删除数据
                if($this->newsModel->deleteAll($where)){
                    //删除旧图
                    foreach($lists as $key=>$value){
                        if($value['new_img']){
                            $old_path = Yii::getAlias('@frontend').'/web'.$value['new_img'];
                            @unlink($old_path);
                        }
                    }
                    $info['code'] = 1;
                    $info['msg'] = "删除成功!";
                    return Json::encode($info);
                }else{
                    $info['code'] = 0;
                    $info['msg'] = "删除失败!";
                    return Json::encode($info);
                }
            }else{
                $info['code'] = 0;
                $info['msg'] = "删除失败!";
                return Json::encode($info);
            }
        }
    }
}